### PR TITLE
Method for verifiing user password in AuthenticationService

### PR DESCRIPTION
**Pull request by vojtabiberle**

### CODE REVIEW

**Comment by Saeven** [comment]
Thanks for this PR!  One question (more of semantics than anything else).  Would it throw BadPasswordException instead of NoSuchUserException?

The user technically is guaranteed to exist since it is a parameter.

**Comment by vojtabiberle** [comment]
You are welcome.

To your question:
I thing this implementation should only throw NoSuchUserException but if we change implementation to this:
```public function verifyPassword(User $user, $password)
    {
        $auth = $this->authenticationProvider->findByUserId($user->getId());
        if (!$auth) {
            throw new NoSuchUserException();
        }

        if (! password_verify($password, $auth->getHash())) {
            throw new BadPasswordException(); 
        }

        return true;
    }```
we can use BadPasswordException too.

**Comment by Saeven** [comment]
Agreed!

**Comment by Saeven** [comment]
If you can add the typehint for password and response, I can merge.


    public function verifyPassword(User $user, string $password): bool
    {
        $auth = $this->authenticationProvider->findByUserId($user->getId());
        if (!$auth) {
            throw new NoSuchUserException();
        }
        return password_verify($password, $auth->getHash());
    }

Thanks again for the contribution.

**Comment by vojtabiberle** [comment]
Ok. And do you want se second implementation with 2 exceptions?

**Comment by Saeven** [comment]
Thanks for offering, I think your current implementation is fine; it's a pattern that's adopted throughout.

**Pull request merged**
