### PR TITLE
implemented functionality to remove a user

### PR DESCRIPTION
**Pull request by Gamewalker**
Dont know if its enough to remove it completly. Its removing it from database and user gets logged out if online.

### CODE REVIEW

**Comment by Saeven** [comment]
@Gamewalker Thanks for the PR!  Are you able to update the specs as well?  Technically should write specs 1st ;)

**Comment by Gamewalker** [comment]
If I would be able to do so, I would be really happy :) 
(sorry I just tried to get some test stuff working in my app and failed, next on my list :( )

**Comment by Saeven** [comment]
Maybe this helps
http://circlical.com/blog/2016/1/30/beginners-introduction-to-phpspec

**Comment by Saeven** [comment]
Too many lifecycle considerations.  After much (years) of deliberation, I feel that forcing users to develop their own deletes is important.

**Pull request closed without merging**
