### PR TITLE
Migrate to laminas

### PR DESCRIPTION
**Pull request by Tigerman55**

### CODE REVIEW

**Comment by CreativeNative** [comment]
When will you merge this?

**Comment by Saeven** [comment]
Funny, I had a feeling it was just a matter of time before I got poked by it as I was merging a few improvements yesterday!  This lib is a critical component for a major production software that we use.  We're in the process of migrating to laminas within that project.  When that's done, I'll have a real testbed to pit this branch against over 900 behat feature tests.  When those tests pass, this gets merged.

I'm thankful for the contribution, just some careful timing, since I may need to continue iterating here, on the ZF3 version.

**Comment by CreativeNative** [comment]
Thank you for your fast response and your good work. I appreciate it a lot. I'm looking forward to hear from you soon. ;-)

**Comment by Saeven** [comment]
Thanks in turn for signaling appreciation!  It's nice to read it!

**Comment by Saeven** [comment]
Thanks, had iterated on master since then - was easier to just run the laminas-migration tool on master. 

Laminas support added with:
https://github.com/Saeven/zf3-circlical-user/pull/64

Appreciate the contrib. 👍

**Pull request closed without merging**
