### PR TITLE
Support for custom cookie names.

### PR DESCRIPTION
**Pull request by vojtabiberle**

### CODE REVIEW

**Comment by Saeven** [comment]
Sorry for the delay!  Been super busy at work.  I do plan to review this shortly.

**Comment by vojtabiberle** [comment]
Thanks for response. You can ask me about detail on Gitter.

**Comment by Saeven** [comment]
This one isn't forgotten!  I think I'm going to propose a pluggable cookie strategy pattern that respects your changes, rather than altering the existing code.  I have a specific instance where I have several auth services working in tandem, but this PR unfortunately breaks that situation.

**Comment by vojtabiberle** [comment]
OK, I agree with you that pluggable strategy will be better solution. Do you have any proposal, how it should work? I can do it and test it.

**Comment by Saeven** [comment]
At its core, I think that:

- a CookieNameProviderInterface can be injected into AuthenticationService as new argument.  
- a StandardCookieNameProvider implementation of CookieNameProviderInterface is injected by default (in cases where the config doesn't exist and no option is specified) by the AuthenticationServiceFactory (checking for Interface implementation on the parameter during construction)
- the default config is modified to specify a new provider, 'cookie_names' => StandardCookieNameProvider, used by the constructor
- then, we add the ability to override config-level providers during build, so that for example, the developer could optionally use: 

```
$container->build( AuthenticationService::class, [ 'providers' => [ 
    'cookie_names' => new CustomNamingStrategy() 
]]);
```

- within AuthenticationService::class, the 4 const cookie names are replaced to lean on the naming strategy provided.


```
interface CookieNameProviderInterface {

    public function getUserCookieName(): string;

    public function getVerificationCookieName(): string;

    public function getRedundancyCookieName(): string;

    public function getHashPrefixName(): string;
}
```

**Comment by vojtabiberle** [comment]
Another PR: https://github.com/Saeven/zf3-circlical-user/pull/33

**Pull request closed without merging**
