### PR TITLE
Bump doctrine package versions

### PR DESCRIPTION
**Pull request by Tigerman55**

### CODE REVIEW

**Comment by Saeven** [comment]
Thanks for submitting!  I haven't dug into the package differences - the configs are identical? No BC breaks?

**Comment by Tigerman55** [comment]
Just spent some additional time looking into it the release history for the bumps. The `doctrine-module` 2 update adds better support for zf3. The `doctrine-orm-module` update supports doctrine module 2 and php 7.2. The `doctrine-orm` update does have minor bc breaks, none of which will affect your library.

My primary reason for bumping these versions is to support doctrine migrations, which is best practice for doctrine schema updates.

**Comment by Tigerman55** [comment]
Have you had a chance to look at this pr more closely? Would much appreciate it if you could look into merging it in.

**Comment by Saeven** [comment]
Sorry Tigerman!  I'm having to check all my projects to see if I can bump, unfortunately I've found one that cannot be resolved.

Could you adjust your PR to use 'or' instead of an absolutely move to 2?

That'd take care of any fringe constraints, and would allow me to merge things right in.

**Comment by Tigerman55** [comment]
Sure thing

**Pull request merged**
