### PR TITLE
Adds updated laminas cache replacement

### PR DESCRIPTION
**Pull request by CreativeNative**
That whole replacement stuff is really dirty and stupid. But nevertheless this will fix it. The problem is, that these replacement options can't exist 2 times.

### CODE REVIEW

**Comment by Saeven** [comment]
No problems, I'm certain this is why I had done it the first time.  But I'm always open to being wrong.  My spidey senses were tingling when I saw this part of your PR.

**Comment by CreativeNative** [comment]
Rofl, spidey senses. ^^ 

Can you please help me once more. I activate the workflow in my fork. Unfortunately it doesn't work, because I don't have a CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}. What's that? Is that a paid service?

Would be cool if that workflow would work also in my fork to check primary and push afterwards. Don't want to bother you.

I want to fix the PSR-4 issue and also the huge coding standard issue. Hope you are ok with that. But that will change a lot of code and I want to be sure that everything is running perfectly. And trust me with that coding standard. This package has to be rock solid and this step will bring it far ahead. I saw a lot of dirty stuff in the code base that has to be cleaned up.

**Comment by Saeven** [comment]
You could probably adjust your workflow to remove CODACY to achieve what you're after yeah.  It is a service that is used to track coverage and style and all kinds of violations.

I have to note, in passing, that while I object to the words "huge coding standard issue", I realize that you have good intentions and appreciate that!

I think 'different' is better. Some parts are beneficial, but the whitespace shenanigans are just imposed preferences.

I work 9-5 Mon/Thursday, and have Fridays for OSS work.  I'll fire up phpcs with your adjustments, and inject exceptions/modifications that  find a middle ground toward the Laminas standard.  I think I largely just object to the whitespace impositions.

Dirty is a strong term.  But I'm happy to hash them out.

**Comment by CreativeNative** [comment]
Please don't get me wrong. This project is really awesome. Since years I'm following it and I'm really happy to use it finally. But I saw a lot of dead code and some other not so nice issues that we could get rid of. ;-)

And this whitespace thing isn't really a big deal. You can also exclude it. I'm more interested in strict types and other security benefits.

**Pull request merged**
